"""make role column in user table not nullable

Revision ID: 679e273714f7
Revises: fe65f453e652
Create Date: 2021-06-06 21:51:31.513351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679e273714f7'
down_revision = 'fe65f453e652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
